### PR TITLE
Remove wrapper div when destroying player

### LINKED ISSUE #656: Bug: Calling .destroy doesn't completely clean the DOM
### Expected Behavior
On already initialized player, calling .destroy should destroy video and remove iframe + positioning div from DOM

### Actual Behavior
Video is not available anymore, including the iframe but the wrapping div of the iframe is still there and calling new Player() after .destroy() creates a stack containing the old div wrapping the iframe in order to position it + new iframe

### Steps to Reproduce
1. Create new player
2. Call .destroy
3. In success promise initialize a new player with different settings

Screenshot_1

### PR DESCRIPTION
**Pull request by rkrishnan8594**
There are some circumstances when the player adds a wrapper `div` around the `iframe` for positioning purposes. This removes that `div` from the DOM when `.destroy` is invoked.

Fixes #656.

### CODE REVIEW

File: src/lib/embed.js [hunk 1]
```diff
@@ -67,6 +67,7 @@ export function createEmbed({ html }, element) {
     const div = document.createElement('div');
     div.innerHTML = html;
 
+    div.firstChild.setAttribute('data-vimeo-wrapper', 'true');
```
Comment (luwes) [inline src/lib/embed.js:70]: would it be possible to not add this data attribute? to not add too much to the DOM

**Review by luwes — APPROVED** [review]
LGTM 👍
