### PR TITLE
Update screenfull to fix fullscreen bug

### LINKED ISSUE #688: Error: Unknown player. Probably unloaded.
Create a player, destroy the player and then create a new player with a new video and then go in fullscreen mode. 
Fullscreen works, but it produces an annoying error in the console:
`Error: Unknown player. Probably unloaded.`

### PR DESCRIPTION
**Pull request by rkrishnan8594**
- Updates screenfull library, which fixes a bug that caused multiple `fullscreenchange` events to be fired, leading to console errors.
- Updates and fixes tests by replacing broken video ID with valid video ID.

Fixes #688.

### CODE REVIEW

**Comment by rkrishnan8594** [comment]
Good call @luwes - updated to remove the event listener on destroy.

File: src/player.js [hunk 1]
```diff
@@ -130,9 +130,8 @@ class Player {
         }
 
         if (screenfull.isEnabled) {
-            const exitFullscreen = () => screenfull.exit();
-
-            screenfull.on('fullscreenchange', () => {
+            this.fullscreenchangeHandler = () => {
+                const exitFullscreen = () => screenfull.exit();
```
Comment (luwes) [inline src/player.js:134]: `const exitFullscreen = () => screenfull.exit();` should be left out of the event listener,
otherwise you're essentially creating new `exitFullscreen` functions on `fullscreenchange` events making the `removeCallback(this, 'event:exitFullscreen', exitFullscreen);` not work as it expects the specific function that was added with `storeCallback(this, 'event:exitFullscreen', exitFullscreen);`

**Review by luwes — APPROVED** [review]
LGTM
